artifacts_root: C:\Users\Roshan\Desktop\Kidney_Classification\Kidney_Tumor_Classification\artifacts


data_ingestion:
  root_dir: C:\Users\Roshan\Desktop\Kidney_Classification\Kidney_Tumor_Classification\artifacts\data_ingestion
  source_URL: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing
  local_data_file: C:\Users\Roshan\Desktop\Kidney_Classification\Kidney_Tumor_Classification\artifacts/data_ingestion/data.zip
  unzip_dir: C:\Users\Roshan\Desktop\Kidney_Classification\Kidney_Tumor_Classification\artifacts\data_ingestion