artifacts_root: C:\Users\Roshan\Desktop\Kidney_Classification\Kidney_Tumor_Classification\artifacts


data_ingestion:
  root_dir: C:\Users\Roshan\Desktop\Kidney_Classification\Kidney_Tumor_Classification\artifacts\data_ingestion
  source_URL: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing
  local_data_file: C:\Users\Roshan\Desktop\Kidney_Classification\Kidney_Tumor_Classification\artifacts/data_ingestion/data.zip
  unzip_dir: C:\Users\Roshan\Desktop\Kidney_Classification\Kidney_Tumor_Classification\artifacts\data_ingestion


prepare_base_model:
  root_dir: C:\Users\Roshan\Desktop\Kidney_Classification\Kidney_Tumor_Classification\artifacts\prepare_base_model
  base_model_path: C:\Users\Roshan\Desktop\Kidney_Classification\Kidney_Tumor_Classification\artifacts\prepare_base_model\base_model.h5
  updated_base_model_path: C:\Users\Roshan\Desktop\Kidney_Classification\Kidney_Tumor_Classification\artifacts\prepare_base_model\base_model_updated.h5